V2
devhatt/hatbot-discord pull request #16
Opened 2023-12-15 19:08 UTC by k1nha

2023-12-15 19:28 UTC, hxsggsz approved these changes

2023-12-15 19:28 UTC, Sherlockzen approved these changes

2023-12-15 19:42 UTC, aalmeida00 requested changes
Vale também aqui o ponto, alterar o eslint/prettier pra corrigir esses detalhes de eof

2023-12-15 19:42 UTC, aalmeida00 commented on .editorconfig
> +insert_final_newline = true
eof

2023-12-15 19:42 UTC, aalmeida00 commented on .prettierrc
> +}
eof

2023-12-15 19:42 UTC, aalmeida00 commented on src/cronjobs/reminder-daily/reminder-daily.ts
> +const octopostRoleId = "1136795129219383376";
vamos mover pra env isso daqui? pra ficar dinamico no futuro

2023-12-15 19:42 UTC, aalmeida00 commented on src/cronjobs/reminder-daily/reminder-daily.ts
> +      if (!pautasOctopost) {
```suggestion
      const agendasOctopost = await GetDailyPages("octopost", 20);

      if (!agendasOctopost) {
```

2023-12-15 19:42 UTC, aalmeida00 commented on src/cronjobs/reminder-daily/reminder-daily.ts
> +        message: `Daily começando em 1h - as 14h\n**Pautas**: ${pautasOctopost.map(
```suggestion
        message: `Daily começando em 1h - as 14h\n**Pautas**: ${agendasOctopost.map(
```

2023-12-15 19:42 UTC, aalmeida00 commented on src/cronjobs/reminder-daily/reminder-daily.ts
> +          (i) => `\n${i}`
Usamos agenda pra referenciar pauta
![image](https://github.com/devhatt/hatbot-discord/assets/61947632/26c3b1be-77a1-4acf-a9d2-915cbe32cebb)


```suggestion
      const agendaPet = await GetDailyPages("petdex", 20);

      if (!agendasPet) {
        return;
      }

      ReminderDaily(client, {
        discordChannel,
        message: `Daily começando em 1h - as 16\n**Pautas:** ${agendasPet.map(
          (i) => `\n${i}`
```

2023-12-15 19:42 UTC, aalmeida00 commented on src/lib/notion.ts
> +      database_id: '7b626c16af1b4f0c986a9811f59cb9a9',
esse id aqui nao é sensível

2023-12-15 19:42 UTC, aalmeida00 commented on src/lib/notion.ts
> +    console.log(err)
A gente pode no futuro logar esses erros no grafana?

2023-12-15 19:42 UTC, aalmeida00 commented on src/utils/index.ts
> +  return octopostsDoDiaAtual[0][object];
Tá em pt-br irmao troca

2023-12-15 21:38 UTC, k1nha commented on src/cronjobs/reminder-daily/reminder-daily.ts
> +const octopostRoleId = "1136795129219383376";
não sei
precisaria colocar no env mesmo não sendo informações sensíveis? pensei em algo como constantes

```ts
export const CONSTANTS = {
    PETDEX:  'key'
    CHANNEL: 'key',
    ...   
}
```

2023-12-15 21:48 UTC, k1nha commented on src/lib/notion.ts
> +      database_id: '7b626c16af1b4f0c986a9811f59cb9a9',
sim, colocarei no env

2023-12-15 21:51 UTC, hxsggsz commented
tem que tirar o comando `"deploy:commands"` e a pasta `configs` dentro de `commands`

2023-12-15 21:52 UTC, k1nha commented on src/lib/notion.ts
> +    console.log(err)
acredito que sim

2023-12-16 00:18 UTC, aalmeida00 commented on src/cronjobs/reminder-daily/reminder-daily.ts
> +const octopostRoleId = "1136795129219383376";
Pode ser, prefiro dessa forma. O foda é se a gente precisar mudar isso, ter que abrir um PR pra mudar isso é osso. E se alguém quiser usar nosso projeto como base pra outro bot no discord?

2023-12-16 02:57 UTC, k1nha commented on src/cronjobs/reminder-daily/reminder-daily.ts
> +const octopostRoleId = "1136795129219383376";
faz sentido
vc tem um ponto

2023-12-16 19:32 UTC, aalmeida00 approved these changes

2023-12-16 19:32 UTC, aalmeida00 commented on src/utils/index.ts
> +  const dailys = arrayDeObjetos.filter((obj) => obj[object])
```suggestion
export function GetRecentDaily(objectArray: any[], object: any): any {
  if (!arrayDeObjetos) {
    return null
  }

  const dailys = arrayDeObjetos.filter((obj) => obj[object])
```

2023-12-18 15:00 UTC, Sherlockzen approved these changes

2023-12-18 15:46 UTC, hxsggsz requested changes

2023-12-18 15:46 UTC, hxsggsz commented on src/utils/index.ts
> +  if (!arrayDeObjetos) {
![image](https://github.com/devhatt/hatbot-discord/assets/103784814/7832c832-d2bc-4718-9ba0-27696d0e5fde)

2023-12-18 15:46 UTC, hxsggsz commented on src/lib/notion.ts
> +    const pautasDaily: string[] = []
![image](https://github.com/devhatt/hatbot-discord/assets/103784814/37a547a7-c915-496a-8e5c-08e9f428e032)

2023-12-19 13:39 UTC, aalmeida00 approved these changes

2023-12-19 14:05 UTC, hxsggsz approved these changes

2023-12-19 14:05 UTC, merged