Issue 28
devhatt/hatbot-discord pull request #29
Opened 2024-01-03 21:58 UTC by k1nha

2024-01-04 15:57 UTC, hxsggsz commented
coloca na descrição do pr `Closes #numero da issue` pra ele fechar a issue quando esse pr for aprovado

2024-01-04 16:02 UTC, hxsggsz requested changes

2024-01-04 16:02 UTC, hxsggsz commented on src/cronjobs/reminder-daily/reminder.ts
> +      throw new Error('Adicione dailys para o reminder')
esse erro ou precisa ser tratado em algum lugar ou precisa virar um console.error, se só tacar o erro assim eu acho que vai quebrar o bot quando cair nessa condição

2024-01-04 16:02 UTC, hxsggsz commented on src/utils/get-recent-daily.ts
> +export function GetRecentDaily(objectArray: any[], object: any): any {
acho que da pra melhorar esse monte de any, colocar unknown talvez e o object ser do tipo object ou Record<string, unknown>

2024-01-04 17:07 UTC, k1nha commented on src/cronjobs/reminder-daily/reminder.ts
> +      throw new Error('Adicione dailys para o reminder')
verdade, não estamos tratando erros
dá pra implementar isso usando webhook do discord

2024-01-04 17:46 UTC, k1nha commented on src/utils/get-recent-daily.ts
> +export function GetRecentDaily(objectArray: any[], object: any): any {
pior que já tentei mudar essa tipagem mas não consegui de maneira alguma tipar, o negocio que a implementação do notion tá meio estranha por conta de como estamos usando as tags no database

2024-01-04 21:11 UTC, aalmeida00 submitted a review, later dismissed

2024-01-04 21:11 UTC, aalmeida00 commented on .eslintrc.json
> +}
eof xd

2024-01-04 21:56 UTC, aalmeida00 approved these changes

2024-01-05 02:18 UTC, hxsggsz approved these changes

2024-01-05 02:19 UTC, merged