add templates for issues and pull requests
devhatt/hatbot-discord pull request #32
Opened 2024-01-08 21:17 UTC by hxsggsz

Closes #4 

add templates for new issues and pull requests

2024-01-08 21:20 UTC, aalmeida00 requested changes

2024-01-08 21:20 UTC, aalmeida00 commented on .github/pull_request_template.md
> +<details>
deixa esse details opened tbm
```suggestion 
<details open> 
```

2024-01-08 21:20 UTC, aalmeida00 commented on .github/pull_request_template.md
> +Closes ID_ISSUE
```suggestion
Closes #ID_ISSUE
```

2024-01-08 21:27 UTC, aalmeida00 approved these changes

2024-01-09 02:44 UTC, k1nha approved these changes

2024-01-09 20:06 UTC, aalmeida00 approved these changes

2024-01-09 20:06 UTC, merged