Fix tag pull request owner when /change or /approve command is called
devhatt/hatbot-discord pull request #33
Opened 2024-01-13 18:54 UTC by aalmeida00

Closes #21

<details> 
  <summary>
    <b>Feature</b>
  </summary>

N/A

</details>

<details open> 
  <summary>
    <b>Bugfix</b>
  </summary>

- **Description**
  N/A

- **Cause**
  N/A

- **Solution**
N/A
</details>

<details> 
  <summary>
    <b>Changelog</b>
  </summary>
N/A
</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

- [x] Issue linked
- [x] Build working correctly
- [ ] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
N/A
</details>

2024-01-13 19:49 UTC, hxsggsz requested changes

2024-01-13 19:49 UTC, hxsggsz commented on src/commands/approve/approve.ts
> +    pullOwner ? pullOwner.user : 'Unknown user'
acho que da pra juntar esses dois ternários no primeiro, talvez o valor inicial dessa variavel ser `unknown user`  ou o else do primeiro ternário ser `unknown user`

2024-01-14 19:45 UTC, k1nha approved these changes

2024-01-19 03:38 UTC, hxsggsz approved these changes

2024-01-19 04:01 UTC, k1nha approved these changes

2024-01-19 04:01 UTC, merged