add open and close on title when the pr is open or closed
devhatt/hatbot-discord pull request #35
Opened 2024-01-17 03:43 UTC by hxsggsz

Closes #34 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

adiciona `{OPEN}` ao titulo da thread de pull request e quando der o comando `/approve` adiciona `{CLOSED}` ao titulo da thread

</details>

<details open> 
  <summary>
    <b>Changelog</b>
  </summary>
mexi no arquivo `pulls.ts` e `approve.ts`
</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

<img width="361" alt="image" src="https://github.com/devhatt/hatbot-discord/assets/103784814/fa3ae099-ec02-4521-939f-e5e5c84c0a6c">

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

- [x] Issue linked
- [x] Build working correctly
- [ ] Tests created
</details>

2024-01-17 12:37 UTC, aalmeida00 approved these changes

2024-01-17 12:37 UTC, aalmeida00 commented on src/commands/approve/approve.ts
> +  }
Mano essa func dá pra se tornar externa recebendo channel e dá pra testar ela sipa de boa.

2024-01-18 02:38 UTC, aalmeida00 requested changes
Pensei agora, esse approve nao tá certo. SE só 1 pessoa mandar /approve ele vai mudar o texto?

2024-01-18 22:01 UTC, aalmeida00 approved these changes

2024-01-19 13:51 UTC, hxsggsz commented on src/commands/pulls/pulls.ts
> +**Pull Request ID:** ${pullID.value}
é github issues isso ai

2024-01-19 13:51 UTC, hxsggsz commented on src/commands/pulls/pulls.ts
> +**Pull Request ID:** ${pullID.value}
é github issues isso ai

2024-01-20 03:38 UTC, k1nha commented on src/commands/approve/utils/getRawThreadName.spec.ts
> +    describe('and the channel is a public thread', () => {
eita, precisa dessa cascata de describe msm? agrupa tudo em um 
```suggestion
describe('getRawThreadName when the message match the regex and the channel is a public thread', () => {

```

2024-01-20 03:38 UTC, k1nha commented on src/commands/approve/utils/getRawThreadName.spec.ts
> +      it('returns the correct value', async () => {
gosto de colocar 

```ts
it('should be return correct value', ...)
```

2024-01-20 04:02 UTC, k1nha requested changes

2024-01-20 04:02 UTC, k1nha commented on src/commands/change/change.ts
>    .setName('change')
```suggestion
  .setName('changes')
```

2024-01-20 04:02 UTC, k1nha commented on src/commands/pulls/utils/pinMessage.spec.ts
acho que dá pra mudar também

2024-01-20 04:02 UTC, k1nha commented on src/utils/bot/get-pull-owner.spec.ts
aqui tbm

2024-01-20 04:02 UTC, k1nha commented on src/utils/bot/prContent.spec.ts
aqui tbmkk

2024-01-20 15:14 UTC, aalmeida00 approved these changes

2024-01-22 17:01 UTC, k1nha approved these changes
pr quente

2024-01-22 19:49 UTC, aalmeida00 approved these changes

2024-01-22 21:52 UTC, merged